Start on instant broker order processing (WIP)
zap-me/beryllium pull request #101
Opened 2022-09-13 03:22 UTC by 4855062503

This is in reference to https://github.com/zap-me/ops/issues/198.

2022-09-15 04:54 UTC, djpnewton requested changes

2022-09-15 04:54 UTC, djpnewton commented on src/tasks.py
> +    utils.yield_gevent()
this is not required as the task will terminate here anyhow

2022-10-26 00:17 UTC, djpnewton commented
updated to be more specific (only update the order in question) and deployed to be-test.bitforge.me

2022-10-26 00:17 UTC, djpnewton approved these changes

2022-10-26 21:39 UTC, eoliveros approved these changes

2022-10-27 03:04 UTC, merged