Start password strength checking for update_password function
zap-me/beryllium pull request #8
Opened 2022-02-07 09:42 UTC by 4855062503

Not yet finished adding strength-checking but works so far.

2022-02-08 01:48 UTC, djpnewton commented
You should use the same password validation code as flask security (so the behaviour is the same in app and on the website)

https://flask-security-too.readthedocs.io/en/stable/patterns.html?highlight=password#password-validation-and-complexity


You can set the settings in `flask_config.py` and use the functions: `flask_security.password_length_validator() flask_security.password_complexity_validator() flask_security.password_breached_validator()`

2022-02-09 02:26 UTC, 4855062503 commented
Do we want to use this function?

https://flask-security-too.readthedocs.io/en/stable/api.html#flask_security.password_breached_validator

Will require an API key

2022-02-09 03:24 UTC, djpnewton commented
> Do we want to use this function?
> 
> https://flask-security-too.readthedocs.io/en/stable/api.html#flask_security.password_breached_validator
> 
> Will require an API key

yep, it will only do something if the setting is conifigured

2022-02-10 02:06 UTC, djpnewton requested changes

2022-02-10 02:06 UTC, djpnewton commented on api_endpoint.py
> +    if (flask_security.password_length_validator(new_password) is not None) or (flask_security.password_complexity_validator(new_password, True) is not None) or (flask_security.password_breached_vali
```suggestion
    if flask_security.password_length_validator(new_password) or flask_security.password_complexity_validator(new_password, True) or flask_security.password_breached_validator(new_password):
```

2022-02-10 08:12 UTC, 4855062503 commented
Updated PR.

2022-02-15 22:45 UTC, djpnewton requested changes
you didnt make all the changes

2022-02-15 22:45 UTC, djpnewton commented on api_endpoint.py
> +    if flask_security.password_length_validator(new_password) is not None or flask_security.password_complexity_validator(new_password, True) is not None or flask_security.password_breached_validator
```suggestion
    if flask_security.password_length_validator(new_password) or flask_security.password_complexity_validator(new_password, True) or flask_security.password_breached_validator(new_password):
```

2022-02-16 02:53 UTC, 4855062503 commented
Updated PR.

2022-02-18 00:14 UTC, merged